### ISSUE TITLE
apparent role dependency jmespath should be documented

### ISSUE THREAD

**Issue by timblaktu** [wcm-io-devops/ansible-jenkins-facts#4]
Running a playbook that invokes your jenkins_plugins role, I get the following error:

```
TASK [wcm_io_devops.jenkins_facts : gather_jenkins_facts : set jenkins facts.] *********************************************************************************************task path: /etc/ansible/roles/wcm_io_devops.jenkins_facts/tasks/gather_jenkins_facts.yml:16
fatal: [jmtest3]: FAILED! =>
  msg: You need to install "jmespath" prior to running json_query filter
```

This is on a fresh Debian 10 VM that has had python 2/3 and pip 2/3 installed. 

I will ensure this machine has jmespath installed via pip 2/3 before proceeding further, but I just wanted to note this here. At the very least, [the Dependencies section of the documentation](https://github.com/wcm-io-devops/ansible-jenkins-facts#dependencies) should indicate this as a dependency.

**Comment by timblaktu** [comment]
Strangely, after installing latest jmespath package using pip and pip3 on the controlled jenkins-master machine, I still get the same error from this role. I have even ssh'ed into the machine to confirm the package is there:

```
ansible@jmtest3:~$ pip3 list | grep jmes
jmespath            0.10.0
ansible@jmtest3:~$ pip list | grep jmes
jmespath            0.10.0
```

**Comment by tobias-richter** [comment]
@timblaktu thank you for pointing this out. I have updated the documentation. We install `jmespath` per default in our controlhosts so we never ran into this issue. 

Since the json_query, which is causing this issue, is evaluated on the control node, you have to install jmespath on the machine where your ansible installation is.
