### ISSUE TITLE
Is Adobe Experience Mgr required?

### ISSUE THREAD

**Issue by timblaktu** [wcm-io-devops/ansible-jenkins-facts#5]
Looking at the [Requirements for this role ](https://github.com/wcm-io-devops/ansible-jenkins-facts/tree/9b832f2e99788a458ef68880f4a9680dab4ec1b7#requirements) I see they indicate:

> The role requires an AEM service that can be controlled with the Ansible service module to be installed on the target machine.

Is this correct? I do not use AEM (I think this means Adobe Experience Mgr?) but the role appears to be working correctly.

**Comment by tobias-richter** [comment]
@timblaktu you are correct, this was an copy and paste issue and was already fixed two days ago in the master.
